# Versión utilizada
version: '3.7'

# Configuración de los servidores que vamos a necesitar
services: 
 
  # servicio MySQL
  # Usa un Dockerfile para cargar los scripts desde Github
  mysql:
    build: mysql/
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_mysql:/var/lib/mysql
    healthcheck: # Hace que los otros servicios esperen hasta que esté listo
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
  #  volumes:
  #   - ./proyecto:/usr/share/phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy # Asegura de que los servicios no fallen al arrancar

  # Servicio de Apache
  apache:
    build: apache/
    ports:
      - 80:80
  #  volumes:
  #   - proyecto:/usr/local/apache2/htdocs
    depends_on:
      - php  

  # Servicio de php
  php:
    build: php/
    ports:
      - 9000:9000
  #  volumes:
  #    - proyecto:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy # Asegura de que los servicios no fallen al arrancar

volumes: 
  database_mysql:
  proyecto:
  

  
